package com.mmikhail.groovy.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build build (050908.2342.55399))

@WebService(targetNamespace = "com:mmikhail:groovy:service",
            name = "sayhello_ptt")
@XmlSeeAlso(
  {
    com.mmikhail.groovy.service.ObjectFactory.class
  })
public interface Sayhello_ptt
{
  @WebMethod
  @SOAPBinding(parameterStyle = ParameterStyle.BARE)
  @Action(output =
          "com:mmikhail:groovy:service/sayhello_ptt/sayhelloResponse",
          input =
          "com:mmikhail:groovy:service/sayhello_ptt/sayhelloRequest")
  @WebResult(targetNamespace = "com:mmikhail:groovy:service",
             name = "string", partName = "response")
  public java.lang.String sayhello(@WebParam(targetNamespace =
                                             "com:mmikhail:groovy:service",
                                             name = "string",
                                             partName = "request")
                                   java.lang.String request);
}
